[package]
name = "appstruct-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "appstruct"
path = "src/main.rs"

[dependencies]
appstruct-codegen.workspace = true
appstruct-compiler.workspace = true
appstruct-ir.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
