use crate::{
    ColumnSchema, DatabaseSchema, DatabaseType, ForeignKeySchema, MigrationPlan, SchemaChange,
    TableSchema,
};
use appstruct_ir::{GeneratedValueIr, OnDeleteIr};

#[must_use]
pub fn initial_migration(schema: &DatabaseSchema) -> String {
    let mut statements = vec![generated_header()];
    statements.extend(schema.tables.iter().map(create_table));
    statements.extend(schema.foreign_keys.iter().map(add_foreign_key));
    format!("{}\n", statements.join("\n"))
}

/// Render SQL for an automatically applicable migration plan.
///
/// # Errors
///
/// Returns an error when the plan contains a blocked or unsupported change.
pub fn migration_sql(plan: &MigrationPlan) -> Result<String, String> {
    if plan.is_blocked() {
        return Err("migration contains changes that require review or input".to_owned());
    }
    let mut statements = vec![generated_header()];
    for planned in &plan.changes {
        statements.push(match &planned.change {
            SchemaChange::AddTable { table } => create_table(table),
            SchemaChange::AddColumn { table, column } => format!(
                "ALTER TABLE {} ADD COLUMN {};\n",
                quote_ident(table),
                column_definition(column)
            ),
            SchemaChange::AlterColumn {
                table,
                before,
                after,
            } => alter_column(table, before, after)?,
            SchemaChange::AddForeignKey { foreign_key } => add_foreign_key(foreign_key),
            SchemaChange::RemoveTable { .. }
            | SchemaChange::RenameTable { .. }
            | SchemaChange::RemoveColumn { .. }
            | SchemaChange::RemoveForeignKey { .. } => {
                return Err("destructive migration cannot be rendered automatically".to_owned());
            }
        });
    }
    Ok(format!("{}\n", statements.join("\n")))
}

fn create_table(table: &TableSchema) -> String {
    let columns = table
        .columns
        .iter()
        .map(column_definition)
        .collect::<Vec<_>>()
        .join(",\n    ");
    format!(
        "CREATE TABLE {} (\n    {columns}\n);\n",
        quote_ident(&table.name)
    )
}

fn column_definition(column: &ColumnSchema) -> String {
    let mut fragments = vec![
        quote_ident(&column.name),
        sql_type(&column.data_type).to_owned(),
    ];
    if matches!(column.generated, Some(GeneratedValueIr::AutoIncrement)) {
        fragments.push("GENERATED BY DEFAULT AS IDENTITY".to_owned());
    }
    if !column.nullable {
        fragments.push("NOT NULL".to_owned());
    }
    if column.primary_key {
        fragments.push("PRIMARY KEY".to_owned());
    } else if column.unique {
        fragments.push("UNIQUE".to_owned());
    }
    if let Some(default) = sql_default(column) {
        fragments.push(format!("DEFAULT {default}"));
    }
    if let DatabaseType::Enum { values } = &column.data_type {
        let choices = values
            .iter()
            .map(|value| quote_literal(value))
            .collect::<Vec<_>>()
            .join(", ");
        fragments.push(format!(
            "CHECK ({} IN ({choices}))",
            quote_ident(&column.name)
        ));
    }
    fragments.join(" ")
}

const fn sql_type(data_type: &DatabaseType) -> &'static str {
    match data_type {
        DatabaseType::Uuid => "UUID",
        DatabaseType::Text | DatabaseType::Enum { .. } => "TEXT",
        DatabaseType::Integer => "INTEGER",
        DatabaseType::Bigint => "BIGINT",
        DatabaseType::Decimal => "NUMERIC",
        DatabaseType::Boolean => "BOOLEAN",
        DatabaseType::Date => "DATE",
        DatabaseType::Datetime => "TIMESTAMPTZ",
        DatabaseType::Json => "JSONB",
    }
}

fn sql_default(column: &ColumnSchema) -> Option<String> {
    if matches!(column.generated, Some(GeneratedValueIr::Now)) {
        return Some("CURRENT_TIMESTAMP".to_owned());
    }
    let value = column.default.as_ref()?;
    Some(match column.data_type {
        DatabaseType::Boolean
        | DatabaseType::Integer
        | DatabaseType::Bigint
        | DatabaseType::Decimal => value.clone(),
        _ => quote_literal(value),
    })
}

fn add_foreign_key(foreign_key: &ForeignKeySchema) -> String {
    let action = match foreign_key.on_delete {
        OnDeleteIr::Restrict => "RESTRICT",
        OnDeleteIr::Cascade => "CASCADE",
        OnDeleteIr::SetNull => "SET NULL",
    };
    let constraint = format!(
        "fk_{}_{}",
        foreign_key.source_table, foreign_key.source_column
    );
    format!(
        "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}) ON DELETE {action};\n",
        quote_ident(&foreign_key.source_table),
        quote_ident(&constraint),
        quote_ident(&foreign_key.source_column),
        quote_ident(&foreign_key.target_table),
        quote_ident(&foreign_key.target_column),
    )
}

fn alter_column(
    table: &str,
    before: &ColumnSchema,
    after: &ColumnSchema,
) -> Result<String, String> {
    if before.name != after.name
        || before.data_type != after.data_type
        || before.primary_key != after.primary_key
        || before.unique != after.unique
        || before.generated != after.generated
    {
        return Err("column shape change requires manual migration".to_owned());
    }
    if before.nullable && !after.nullable {
        return Err("adding a not-null constraint requires manual migration".to_owned());
    }
    let prefix = format!(
        "ALTER TABLE {} ALTER COLUMN {}",
        quote_ident(table),
        quote_ident(&after.name)
    );
    let mut statements = Vec::new();
    if before.nullable != after.nullable {
        statements.push(format!("{prefix} DROP NOT NULL;\n"));
    }
    if before.default != after.default {
        statements.push(sql_default(after).map_or_else(
            || format!("{prefix} DROP DEFAULT;\n"),
            |default| format!("{prefix} SET DEFAULT {default};\n"),
        ));
    }
    Ok(statements.concat())
}

fn generated_header() -> String {
    "-- @generated by AppStruct. Review before applying.\n".to_owned()
}

fn quote_ident(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_sql_values() {
        assert_eq!(quote_ident("project\"name"), "\"project\"\"name\"");
        assert_eq!(quote_literal("it's"), "'it''s'");
    }
}
